In [3]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import datetime
import requests
from bs4 import BeautifulSoup as bs
from selenium import webdriver
from selenium.webdriver.common.by import By

In [8]:
driver = webdriver.Chrome()
url = "https://flight.easemytrip.com/FlightList/Index?srch=DEL-Delhi-India|BOM-Mumbai-India|10/11/2023&px=1-0-0&cbn=2&ar=undefined&isow=true&isdm=true&lang=en-us&utm_campaign=788997081&utm_source=g_c&utm_medium=cpc&utm_term=e_easemytrip&adgroupid=39319940377&gclid=CjwKCAjw15eqBhBZEiwAbDomEjfx50BOmAr8rbAJ5jP2sKUCtHdk8Gohs1PmjmVAdpXveE2ntD_4ERoCfhwQAvD_BwE&IsDoubleSeat=false&CCODE=IN&curr=INR&apptype=B2C"
driver.get(url)

# Multiple URLS

In [100]:
urls = []

In [101]:
def url_link(base_url):
    start_date = datetime.date(2023, 11, 15)
    end_date = datetime.date(2024, 1, 4)   
    current_date = start_date
    while current_date <= end_date:
        formatted_date = current_date.strftime("%d/%m/%Y")
        url = base_url.format(formatted_date)
        today = datetime.date.today()
        days_left = (current_date - today).days
        urls.append((url, days_left))
        current_date += datetime.timedelta(days=1)

In [102]:

url_link("https://flight.easemytrip.com/FlightList/Index?srch=DEL-Delhi-India|BOM-Mumbai-India|{}&px=1-0-0&cbn=2&ar=undefined&isow=true&isdm=true&lang=en-us&CouponCode=&ompAff=&bc=&ISWL=&isRL=true&CCODE=IN&curr=INR&apptype=B2C")
url_link("https://flight.easemytrip.com/FlightList/Index?srch=DEL-Delhi-India|BLR-Bangalore-India|{}&px=1-0-0&cbn=2&ar=undefined&isow=true&isdm=true&lang=en-us&CouponCode=&ompAff=&bc=&ISWL=&isRL=true&CCODE=IN&curr=INR&apptype=B2C")
url_link("https://flight.easemytrip.com/FlightList/Index?srch=DEL-Delhi-India|BLR-Bangalore-India|{}&px=1-0-0&cbn=2&ar=undefined&isow=true&isdm=true&lang=en-us&CouponCode=&ompAff=&bc=&ISWL=&isRL=true&CCODE=IN&curr=INR&apptype=B2C")
url_link("https://flight.easemytrip.com/FlightList/Index?srch=DEL-Delhi-India|HYD-Hyderabad-India|{}&px=1-0-0&cbn=2&ar=undefined&isow=true&isdm=true&lang=en-us&CouponCode=&ompAff=&bc=&ISWL=&isRL=true&CCODE=IN&curr=INR&apptype=B2C")
url_link("https://flight.easemytrip.com/FlightList/Index?srch=DEL-Delhi-India|MAA-Chennai-India|{}&px=1-0-0&cbn=2&ar=undefined&isow=true&isdm=true&lang=en-us&CouponCode=&ompAff=&bc=&ISWL=&isRL=true&CCODE=IN&curr=INR&apptype=B2C")


url_link("https://flight.easemytrip.com/FlightList/Index?srch=BOM-Mumbai-India|DEL-Delhi-India|{}&px=1-0-0&cbn=2&ar=undefined&isow=true&isdm=true&lang=en-us&CouponCode=&ompAff=&bc=&ISWL=&isRL=true&CCODE=IN&curr=INR&apptype=B2C")
url_link("https://flight.easemytrip.com/FlightList/Index?srch=BOM-Mumbai-India|BLR-Bangalore-India|{}&px=1-0-0&cbn=2&ar=undefined&isow=true&isdm=true&lang=en-us&CouponCode=&ompAff=&bc=&ISWL=&isRL=true&CCODE=IN&curr=INR&apptype=B2C")
url_link("https://flight.easemytrip.com/FlightList/Index?srch=BOM-Mumbai-India|CCU-Kolkata-India|{}&px=1-0-0&cbn=2&ar=undefined&isow=true&isdm=true&lang=en-us&CouponCode=&ompAff=&bc=&ISWL=&isRL=true&CCODE=IN&curr=INR&apptype=B2C")
url_link("https://flight.easemytrip.com/FlightList/Index?srch=BOM-Mumbai-India|HYD-Hyderabad-India|{}&px=1-0-0&cbn=2&ar=undefined&isow=true&isdm=true&lang=en-us&CouponCode=&ompAff=&bc=&ISWL=&isRL=true&CCODE=IN&curr=INR&apptype=B2C")
url_link("https://flight.easemytrip.com/FlightList/Index?srch=BOM-Mumbai-India|MAA-Chennai-India|{}&px=1-0-0&cbn=2&ar=undefined&isow=true&isdm=true&lang=en-us&CouponCode=&ompAff=&bc=&ISWL=&isRL=true&CCODE=IN&curr=INR&apptype=B2C")


url_link("https://flight.easemytrip.com/FlightList/Index?srch=CCU-Kolkata-India|DEL-Delhi-India|{}&px=1-0-0&cbn=2&ar=undefined&isow=true&isdm=true&lang=en-us&CouponCode=&ompAff=&bc=&ISWL=&isRL=true&CCODE=IN&curr=INR&apptype=B2C")
url_link("https://flight.easemytrip.com/FlightList/Index?srch=CCU-Kolkata-India|BLR-Bangalore-India|{}&px=1-0-0&cbn=2&ar=undefined&isow=true&isdm=true&lang=en-us&CouponCode=&ompAff=&bc=&ISWL=&isRL=true&CCODE=IN&curr=INR&apptype=B2C")
url_link("https://flight.easemytrip.com/FlightList/Index?srch=CCU-Kolkata-India|HYD-Hyderabad-India|{}&px=1-0-0&cbn=2&ar=undefined&isow=true&isdm=true&lang=en-us&CouponCode=&ompAff=&bc=&ISWL=&isRL=true&CCODE=IN&curr=INR&apptype=B2C")
url_link("https://flight.easemytrip.com/FlightList/Index?srch=CCU-Kolkata-India|MAA-Chennai-India|{}&px=1-0-0&cbn=2&ar=undefined&isow=true&isdm=true&lang=en-us&CouponCode=&ompAff=&bc=&ISWL=&isRL=true&CCODE=IN&curr=INR&apptype=B2C")
url_link("https://flight.easemytrip.com/FlightList/Index?srch=CCU-Kolkata-India|BOM-Mumbai-India|{}&px=1-0-0&cbn=2&ar=undefined&isow=true&isdm=true&lang=en-us&CouponCode=&ompAff=&bc=&ISWL=&isRL=true&CCODE=IN&curr=INR&apptype=B2C")


url_link("https://flight.easemytrip.com/FlightList/Index?srch=BLR-Bangalore-India|DEL-Delhi-India|{}&px=1-0-0&cbn=2&ar=undefined&isow=true&isdm=true&lang=en-us&CouponCode=&ompAff=&bc=&ISWL=&isRL=true&CCODE=IN&curr=INR&apptype=B2C")
url_link("https://flight.easemytrip.com/FlightList/Index?srch=BLR-Bangalore-India|BOM-Mumbai-India|{}&px=1-0-0&cbn=2&ar=undefined&isow=true&isdm=true&lang=en-us&CouponCode=&ompAff=&bc=&ISWL=&isRL=true&CCODE=IN&curr=INR&apptype=B2C")
url_link("https://flight.easemytrip.com/FlightList/Index?srch=BLR-Bangalore-India|HYD-Hyderabad-India|{}&px=1-0-0&cbn=2&ar=undefined&isow=true&isdm=true&lang=en-us&CouponCode=&ompAff=&bc=&ISWL=&isRL=true&CCODE=IN&curr=INR&apptype=B2C")
url_link("https://flight.easemytrip.com/FlightList/Index?srch=BLR-Bangalore-India|MAA-Chennai-India|{}&px=1-0-0&cbn=2&ar=undefined&isow=true&isdm=true&lang=en-us&CouponCode=&ompAff=&bc=&ISWL=&isRL=true&CCODE=IN&curr=INR&apptype=B2C")
url_link("https://flight.easemytrip.com/FlightList/Index?srch=BLR-Bangalore-India|CCU-Kolkata-India|{}&px=1-0-0&cbn=2&ar=undefined&isow=true&isdm=true&lang=en-us&CouponCode=&ompAff=&bc=&ISWL=&isRL=true&CCODE=IN&curr=INR&apptype=B2C")


url_link("https://flight.easemytrip.com/FlightList/Index?srch=MAA-Chennai-India|DEL-Delhi-India|{}&px=1-0-0&cbn=2&ar=undefined&isow=true&isdm=true&lang=en-us&CouponCode=&ompAff=&bc=&ISWL=&isRL=true&CCODE=IN&curr=INR&apptype=B2C")
url_link("https://flight.easemytrip.com/FlightList/Index?srch=MAA-Chennai-India|BOM-Mumbai-India|{}&px=1-0-0&cbn=2&ar=undefined&isow=true&isdm=true&lang=en-us&CouponCode=&ompAff=&bc=&ISWL=&isRL=true&CCODE=IN&curr=INR&apptype=B2C")
url_link("https://flight.easemytrip.com/FlightList/Index?srch=MAA-Chennai-India|HYD-Hyderabad-India|{}&px=1-0-0&cbn=2&ar=undefined&isow=true&isdm=true&lang=en-us&CouponCode=&ompAff=&bc=&ISWL=&isRL=true&CCODE=IN&curr=INR&apptype=B2C")
url_link("https://flight.easemytrip.com/FlightList/Index?srch=MAA-Chennai-India|CCU-Kolkata-India|{}&px=1-0-0&cbn=2&ar=undefined&isow=true&isdm=true&lang=en-us&CouponCode=&ompAff=&bc=&ISWL=&isRL=true&CCODE=IN&curr=INR&apptype=B2C")
url_link("https://flight.easemytrip.com/FlightList/Index?srch=MAA-Chennai-India|BLR-Bangalore-India|{}&px=1-0-0&cbn=2&ar=undefined&isow=true&isdm=true&lang=en-us&CouponCode=&ompAff=&bc=&ISWL=&isRL=true&CCODE=IN&curr=INR&apptype=B2C")


url_link("https://flight.easemytrip.com/FlightList/Index?srch=HYD-Hyderabad-India|DEL-Delhi-India|{}&px=1-0-0&cbn=2&ar=undefined&isow=true&isdm=true&lang=en-us&CouponCode=&ompAff=&bc=&ISWL=&isRL=true&CCODE=IN&curr=INR&apptype=B2C")
url_link("https://flight.easemytrip.com/FlightList/Index?srch=HYD-Hyderabad-India|BOM-Mumbai-India|{}&px=1-0-0&cbn=2&ar=undefined&isow=true&isdm=true&lang=en-us&CouponCode=&ompAff=&bc=&ISWL=&isRL=true&CCODE=IN&curr=INR&apptype=B2C")
url_link("https://flight.easemytrip.com/FlightList/Index?srch=HYD-Hyderabad-India|CCU-Kolkata-India|{}&px=1-0-0&cbn=2&ar=undefined&isow=true&isdm=true&lang=en-us&CouponCode=&ompAff=&bc=&ISWL=&isRL=true&CCODE=IN&curr=INR&apptype=B2C")
url_link("https://flight.easemytrip.com/FlightList/Index?srch=HYD-Hyderabad-India|BLR-Bangalore-India|{}&px=1-0-0&cbn=2&ar=undefined&isow=true&isdm=true&lang=en-us&CouponCode=&ompAff=&bc=&ISWL=&isRL=true&CCODE=IN&curr=INR&apptype=B2C")
url_link("https://flight.easemytrip.com/FlightList/Index?srch=HYD-Hyderabad-India|MAA-Chennai-India|{}&px=1-0-0&cbn=2&ar=undefined&isow=true&isdm=true&lang=en-us&CouponCode=&ompAff=&bc=&ISWL=&isRL=true&CCODE=IN&curr=INR&apptype=B2C")

In [105]:
driver = webdriver.Chrome()

air_lines = []
flight_number = []
source_city = []
source_time = []
destination_city = []
destination_time = []
duration = []
days_left = []
stops = []
price = []

for url in urls:
    driver.get(url[0])
    days_left.append(url[1])
    class_name1 = "airl-txt-n"
    elements = driver.find_elements(By.CLASS_NAME, class_name1)
    for element in elements:
        split_al = element.text.split('\n')
        air_lines.append(split_al[0])
        flight_number.append(split_al[1])
        
    class_name2 = "top5"
    elements = driver.find_elements(By.CLASS_NAME, class_name2)
    for i in range(0, len(elements), 2):
        split_sl = elements[i].text.split('\n')
        source_time.append(split_sl[0])
        source_city.append(split_sl[1])
    for i in range(1, len(elements), 2):
        split_sl = elements[i].text.split('\n')
        destination_time.append(split_sl[0])
        destination_city.append(split_sl[1])
    
    class_name3 = "non-st"
    elements = driver.find_elements(By.CLASS_NAME, class_name3)
    for element in elements:
        split_du = element.text.split('\n')
        duration.append(split_du[0])
        stops.append(split_du[1])
    
    class_name4 = "cle"
    elements = driver.find_elements(By.CLASS_NAME, class_name4)
    for element in elements:
        split_pr = element.text.split('\n')
        price.append(split_pr[0])

In [207]:
df = pd.DataFrame({'airline': air_lines, 'flight': flight_number, 'source_city': source_city, 
                         'departure_time': source_time, 'stops': stops, 'arrival_time': destination_time, 
                        'destination_city': destination_city, 'class': 'Business', 
                   'duration': duration, 'days_left': days_left, 'price': price})

In [216]:
df.head()

,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,Air India,AI-768,Kolkata,17:55,1-stop,11:00,Chennai,Business,17h 05m,1,"55,123"
1,Vistara,UK-938,Mumbai,10:00,1-stop,23:35,Chennai,Business,13h 35m,1,"49,589"
2,Vistara,UK-802,Bangalore,06:40,1-stop,07:30,Hyderabad,Business,06h 20m,1,"75,729"
3,Vistara,UK-706,Kolkata,20:40,1-stop,07:45,Bangalore,Business,11h 05m,1,"69,280"
4,Air India,AI-698,Hyderabad,22:30,1-stop,07:15,Chennai,Business,06h 10m,1,"66,952"

In [255]:
def label_time_of_day(time_str):
    hour = int(time_str.split(':')[0])
    if 0 <= hour < 3:
        return 'Late_Night'
    elif 3 <= hour < 6:
        return 'Early_Morning'
    elif 6 <= hour < 12:
        return 'Morning'
    elif 12 <= hour < 17:
        return 'Afternoon'
    elif 17 <= hour < 21:
        return 'Evening'
    else:
        return 'Night'

In [256]:
df.departure_time = df.departure_time.apply(label_time_of_day)
df.arrival_time = df.arrival_time.apply(label_time_of_day)

In [257]:
def stop_conversion(description):
    if 'non-stop' in description:
        return 'zero'
    elif '1-stop' in description:
        return 'one'
    else:
        return 'two_or_more'

In [258]:
df.stops = df.stops.apply(stop_conversion)

In [259]:
def duration_conversion(duration):
    hours, minutes = duration.split()
    hours = int(hours[:-1]) 
    minutes = int(minutes[:-1]) 
    decimal_hours = hours + (minutes / 60)
    return round(decimal_hours, 2)

In [260]:
df.duration = df.duration.apply(duration_conversion)

In [261]:
df.price = df.price.apply(lambda x: int(x.replace(',', '')))

In [267]:
df.head()

,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,Vistara,UK-955,Delhi,Evening,one,Morning,Bangalore,Business,15.08,1,59413
1,Air India,AI-544,Delhi,Afternoon,one,Late_Night,Mumbai,Business,7.33,1,41112
2,Air India,AI-516,Bangalore,Morning,one,Evening,Mumbai,Business,12.08,1,74945
3,Air India,AI-640,Bangalore,Morning,one,Night,Mumbai,Business,6.08,1,74945
4,Vistara,UK-835,Delhi,Evening,one,Morning,Chennai,Business,12.33,1,98512

In [274]:
df.to_csv("C:/Users/shivp/Python/Project/Flight/flight_dataset.csv", index=False)